let cities=['Pune','Rourkela','Banglore'];
cities[3]='Bhubaneswar';
cities[4]='Mumbai';
console.log(cities);
let length=cities.length;
cities.unshift('Chennai');
cities.unshift('Delhi');
cities.push('Kolkata');
console.log(cities);
cities.pop();
cities.pop();
console.log(cities);
console.log(cities.lenght);